In [1]:
import joblib
import numpy as np



In [2]:
import Percepcion as p
perceptor = p.Percepcion()

In [3]:
import cv2

img = cv2.imread("images/man-2.png")
segmented = perceptor.procesarimagen(img)
print("processed")


p = np.where(img == 255, img, segmented)
print(p)
cv2.imshow("segmented", p)
cv2.waitKey(1)

processed
[[[255. 255. 255.]
  [255. 255. 255.]
  [255.   0.   0.]
  ...
  [255.   0.   0.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255.   0.   0.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255.   0.   0.]
  [255. 255. 255.]]

 [[255.   0.   0.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255.   0.   0.]]

 ...

 [[255.   0.   0.]
  [255.   0.   0.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255.   0.   0.]
  [255.   0.   0.]]

 [[255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  ...
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]]

 [[255. 255. 255.]
  [255.   0.   0.]
  [255.   0.   0.]
  ...
  [255.   0.   0.]
  [255.   0.   0.]
  [255. 255. 255.]]]


-1